/**
 * GitHub Service Tests
 *
 * Unit tests for the GitHub push integration service.
 * These tests mock the Octokit client to avoid real API calls.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { GitHubServiceError } from './githubService';

// Build mock instance with all needed methods
const mockUsers = { getAuthenticated: vi.fn() };
const mockRepos = { createForAuthenticatedUser: vi.fn() };
const mockGit = {
  getRef: vi.fn(),
  getCommit: vi.fn(),
  createBlob: vi.fn(),
  createTree: vi.fn(),
  createCommit: vi.fn(),
  updateRef: vi.fn(),
};

vi.mock('@octokit/rest', () => ({
  Octokit: vi.fn().mockImplementation(() => ({
    users: mockUsers,
    repos: mockRepos,
    git: mockGit,
  })),
}));

vi.mock('../templates', () => ({
  ProjectTemplateGenerator: vi.fn().mockImplementation(() => ({
    generateProject: vi.fn().mockResolvedValue([
      { path: 'README.md', content: '# Test Project' },
      { path: 'package.json', content: '{"name": "test"}' },
    ]),
  })),
}));

import { pushProjectToGitHub } from './githubService';

describe('GitHubService', () => {
  const defaultOptions = {
    token: 'ghp_test123',
    repoName: 'my-qa-project',
    isPrivate: false,
    description: 'Test project',
    projectConfig: {
      projectName: 'my-qa-project',
      testingType: 'web' as const,
      framework: 'selenium',
      language: 'java',
      testRunner: 'testng',
      buildTool: 'maven',
      testingPattern: 'page-object-model',
      utilities: {
        configReader: false,
        jsonReader: false,
        screenshotUtility: false,
        logger: false,
        dataProvider: false,
        faker: false,
        includeDocker: false,
        includeDockerCompose: false,
      },
      includeSampleTests: true,
    },
  };

  beforeEach(() => {
    vi.clearAllMocks();

    // Setup default happy-path mocks
    mockUsers.getAuthenticated.mockResolvedValue({
      data: { login: 'testuser' },
    });

    mockRepos.createForAuthenticatedUser.mockResolvedValue({
      data: {
        owner: { login: 'testuser' },
        name: 'my-qa-project',
        html_url: 'https://github.com/testuser/my-qa-project',
        clone_url: 'https://github.com/testuser/my-qa-project.git',
        default_branch: 'main',
      },
    });

    mockGit.getRef.mockResolvedValue({
      data: { object: { sha: 'abc123' } },
    });

    mockGit.getCommit.mockResolvedValue({
      data: { tree: { sha: 'tree123' } },
    });

    mockGit.createBlob.mockResolvedValue({
      data: { sha: 'blob123' },
    });

    mockGit.createTree.mockResolvedValue({
      data: { sha: 'newtree123' },
    });

    mockGit.createCommit.mockResolvedValue({
      data: { sha: 'newcommit123' },
    });

    mockGit.updateRef.mockResolvedValue({
      data: {},
    });
  });

  describe('pushProjectToGitHub', () => {
    it('should successfully push a project to GitHub', async () => {
      const result = await pushProjectToGitHub(defaultOptions);

      expect(result).toEqual({
        repoUrl: 'https://github.com/testuser/my-qa-project',
        cloneUrl: 'https://github.com/testuser/my-qa-project.git',
        fullName: 'testuser/my-qa-project',
        filesCount: 2,
        defaultBranch: 'main',
      });
    });

    it('should validate token first', async () => {
      await pushProjectToGitHub(defaultOptions);
      expect(mockUsers.getAuthenticated).toHaveBeenCalledTimes(1);
    });

    it('should create repository with correct parameters', async () => {
      await pushProjectToGitHub(defaultOptions);

      expect(mockRepos.createForAuthenticatedUser).toHaveBeenCalledWith({
        name: 'my-qa-project',
        description: 'Test project',
        private: false,
        auto_init: true,
        gitignore_template: undefined,
      });
    });

    it('should create blobs for each generated file', async () => {
      await pushProjectToGitHub(defaultOptions);
      // 2 files generated by mock
      expect(mockGit.createBlob).toHaveBeenCalledTimes(2);
    });

    it('should create a single commit with all files', async () => {
      await pushProjectToGitHub(defaultOptions);
      expect(mockGit.createTree).toHaveBeenCalledTimes(1);
      expect(mockGit.createCommit).toHaveBeenCalledTimes(1);
      expect(mockGit.updateRef).toHaveBeenCalledTimes(1);
    });

    it('should throw GitHubServiceError on invalid token', async () => {
      mockUsers.getAuthenticated.mockRejectedValue({
        status: 401,
        message: 'Bad credentials',
      });

      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(GitHubServiceError);
      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(/Invalid GitHub token/);
    });

    it('should throw GitHubServiceError when repo already exists', async () => {
      mockRepos.createForAuthenticatedUser.mockRejectedValue({
        status: 422,
        response: {
          data: {
            errors: [{ message: 'name already exists on this account' }],
          },
        },
        message: 'Validation Failed',
      });

      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(/already exists/);
    });

    it('should throw GitHubServiceError on insufficient permissions', async () => {
      mockUsers.getAuthenticated.mockRejectedValue({
        status: 403,
        message: 'Forbidden',
      });

      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(
        /lacks required permissions/
      );
    });

    it('should handle private repos correctly', async () => {
      await pushProjectToGitHub({ ...defaultOptions, isPrivate: true });

      expect(mockRepos.createForAuthenticatedUser).toHaveBeenCalledWith(
        expect.objectContaining({ private: true })
      );
    });

    it('should use default description when none provided', async () => {
      const opts = { ...defaultOptions, description: undefined };
      await pushProjectToGitHub(opts);

      expect(mockRepos.createForAuthenticatedUser).toHaveBeenCalledWith(
        expect.objectContaining({
          description: 'QA automation project generated by QAStarter',
        })
      );
    });

    it('should throw GitHubServiceError when createTree fails', async () => {
      mockGit.createTree.mockRejectedValue({
        status: 500,
        message: 'Internal Server Error',
      });

      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(/Failed to push files/);
    });

    it('should throw GitHubServiceError on network error during push', async () => {
      mockGit.createBlob.mockRejectedValue(
        new Error('fetch failed')
      );

      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(GitHubServiceError);
      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(/Failed to push files/);
    });

    it('should pass correct blob encoding (base64)', async () => {
      await pushProjectToGitHub(defaultOptions);

      expect(mockGit.createBlob).toHaveBeenCalledWith(
        expect.objectContaining({
          encoding: 'base64',
        })
      );
    });

    it('should throw GitHubServiceError for invalid repo name (422 without already-exists)', async () => {
      mockRepos.createForAuthenticatedUser.mockRejectedValue({
        status: 422,
        response: {
          data: {
            errors: [{ message: 'name is too long' }],
          },
        },
        message: 'Validation Failed',
      });

      await expect(pushProjectToGitHub(defaultOptions)).rejects.toThrow(/Invalid repository name/);
    });
  });

  describe('GitHubServiceError', () => {
    it('should have correct properties', () => {
      const error = new GitHubServiceError('Test error', 'TEST_CODE');
      expect(error.message).toBe('Test error');
      expect(error.errorCode).toBe('TEST_CODE');
      expect(error.name).toBe('GitHubServiceError');
      expect(error).toBeInstanceOf(Error);
    });
  });
});
