/**
 * GitHub Integration Service
 *
 * Handles creating GitHub repositories and pushing generated project files.
 * Uses the GitHub Git Data API (blobs → tree → commit → ref) to push all files
 * in a single commit, which is efficient and atomic.
 */

import { Octokit } from '@octokit/rest';
import { ProjectConfig } from '@shared/schema';
import { ProjectTemplateGenerator, TemplateFile } from '../templates';
import path from 'path';
import { logger } from '../utils/logger';

export interface GitHubPushOptions {
  /** GitHub Personal Access Token with 'repo' scope */
  token: string;
  /** Repository name (e.g., "my-qa-project") */
  repoName: string;
  /** Whether the repo should be private */
  isPrivate: boolean;
  /** Optional repository description */
  description?: string;
  /** Project configuration for generating files */
  projectConfig: ProjectConfig;
}

export interface GitHubPushResult {
  /** Full repository URL */
  repoUrl: string;
  /** Git clone URL (HTTPS) */
  cloneUrl: string;
  /** Owner/repo slug */
  fullName: string;
  /** Number of files pushed */
  filesCount: number;
  /** Default branch name */
  defaultBranch: string;
}

/**
 * Validates that the provided GitHub token has necessary scopes
 * by making a simple authenticated request.
 */
async function validateToken(octokit: Octokit): Promise<{ login: string }> {
  try {
    const { data } = await octokit.users.getAuthenticated();
    return { login: data.login };
  } catch (error: any) {
    if (error.status === 401) {
      throw new GitHubServiceError(
        'Invalid GitHub token. Please check your Personal Access Token.',
        'AUTH_FAILED'
      );
    }
    if (error.status === 403) {
      throw new GitHubServiceError(
        'GitHub token lacks required permissions. Ensure it has the "repo" scope.',
        'INSUFFICIENT_SCOPE'
      );
    }
    throw new GitHubServiceError(
      `GitHub authentication failed: ${error.message}`,
      'AUTH_FAILED'
    );
  }
}

/**
 * Creates a new GitHub repository.
 */
async function createRepository(
  octokit: Octokit,
  repoName: string,
  isPrivate: boolean,
  description?: string
): Promise<{ owner: string; repo: string; htmlUrl: string; cloneUrl: string; defaultBranch: string }> {
  try {
    const { data } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: description || `QA automation project generated by QAStarter`,
      private: isPrivate,
      auto_init: true, // Creates initial commit with README so we have a branch to push to
      gitignore_template: undefined, // We provide our own .gitignore
    });

    return {
      owner: data.owner.login,
      repo: data.name,
      htmlUrl: data.html_url,
      cloneUrl: data.clone_url,
      defaultBranch: data.default_branch,
    };
  } catch (error: any) {
    if (error.status === 422) {
      // Repository already exists or name is invalid
      const message = error.response?.data?.errors?.[0]?.message || error.message;
      if (message.includes('already exists')) {
        throw new GitHubServiceError(
          `Repository "${repoName}" already exists. Please choose a different name.`,
          'REPO_EXISTS'
        );
      }
      throw new GitHubServiceError(
        `Invalid repository name: ${message}`,
        'INVALID_REPO_NAME'
      );
    }
    throw new GitHubServiceError(
      `Failed to create repository: ${error.message}`,
      'REPO_CREATE_FAILED'
    );
  }
}

/**
 * Retries an async operation with exponential backoff.
 * Used to handle the race condition where GitHub's `auto_init` commit
 * hasn't fully propagated before we try to read the branch ref.
 */
async function withRetry<T>(
  fn: () => Promise<T>,
  maxRetries: number = 3,
  baseDelayMs: number = 1000
): Promise<T> {
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error) {
      if (attempt === maxRetries) throw error;
      const delay = baseDelayMs * Math.pow(2, attempt);
      logger.debug(`Retry attempt ${attempt + 1}/${maxRetries} after ${delay}ms`);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }
  // TypeScript: unreachable but required for exhaustive return
  throw new Error('withRetry exhausted');
}

/**
 * Pushes all generated project files to the repository in a single commit
 * using the Git Data API (blobs → tree → commit → ref update).
 */
async function pushFilesToRepo(
  octokit: Octokit,
  owner: string,
  repo: string,
  defaultBranch: string,
  files: TemplateFile[]
): Promise<number> {
  try {
    // 1. Get the current commit SHA (HEAD of default branch)
    //    Retry to handle race condition with auto_init not yet propagated
    const { data: refData } = await withRetry(() =>
      octokit.git.getRef({
        owner,
        repo,
        ref: `heads/${defaultBranch}`,
      })
    );
    const latestCommitSha = refData.object.sha;

    // 2. Get the tree SHA of the latest commit
    const { data: commitData } = await octokit.git.getCommit({
      owner,
      repo,
      commit_sha: latestCommitSha,
    });
    const baseTreeSha = commitData.tree.sha;

    // 3. Create blobs in batches (parallel with concurrency limit)
    const BATCH_SIZE = 5;
    const treeEntries: Array<{
      path: string;
      mode: '100644' | '100755';
      type: 'blob';
      sha: string;
    }> = [];

    for (let i = 0; i < files.length; i += BATCH_SIZE) {
      const batch = files.slice(i, i + BATCH_SIZE);
      const blobResults = await Promise.all(
        batch.map(async (file) => {
          // Buffer content (binary assets like gradle-wrapper.jar) is
          // base64-encoded directly; text content is first UTF-8 encoded.
          const contentBase64 = Buffer.isBuffer(file.content)
            ? file.content.toString('base64')
            : Buffer.from(file.content, 'utf-8').toString('base64');
          const { data: blobData } = await octokit.git.createBlob({
            owner,
            repo,
            content: contentBase64,
            encoding: 'base64',
          });

          // Determine file mode (executable for shell scripts and gradlew)
          const isExecutable =
            file.path.endsWith('.sh') ||
            file.path === 'gradlew' ||
            file.path.endsWith('/gradlew');

          return {
            path: file.path,
            mode: (isExecutable ? '100755' : '100644') as '100644' | '100755',
            type: 'blob' as const,
            sha: blobData.sha,
          };
        })
      );
      treeEntries.push(...blobResults);
    }

    // 4. Create a new tree with all files
    const { data: newTree } = await octokit.git.createTree({
      owner,
      repo,
      base_tree: baseTreeSha,
      tree: treeEntries,
    });

    // 5. Create a new commit pointing to the new tree
    const { data: newCommit } = await octokit.git.createCommit({
      owner,
      repo,
      message: 'Initial project scaffold\n\nGenerated by QAStarter (https://qastarter.dev)',
      tree: newTree.sha,
      parents: [latestCommitSha],
    });

    // 6. Update the default branch reference to point to the new commit
    await octokit.git.updateRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
      sha: newCommit.sha,
    });

    return files.length;
  } catch (error: any) {
    // Wrap raw Octokit/network errors with meaningful context
    if (error instanceof GitHubServiceError) throw error;

    const statusHint = error.status ? ` (HTTP ${error.status})` : '';
    throw new GitHubServiceError(
      `Failed to push files to repository${statusHint}: ${error.message}`,
      'PUSH_FAILED'
    );
  }
}

/**
 * Main entry point: generates the project and pushes it to a new GitHub repo.
 */
export async function pushProjectToGitHub(
  options: GitHubPushOptions
): Promise<GitHubPushResult> {
  const octokit = new Octokit({ auth: options.token });

  // 1. Validate token
  logger.info('Validating GitHub token...');
  const { login } = await validateToken(octokit);
  logger.info(`Authenticated as GitHub user: ${login}`);

  // 2. Create repository
  logger.info(`Creating repository: ${options.repoName}`);
  const repoInfo = await createRepository(
    octokit,
    options.repoName,
    options.isPrivate,
    options.description
  );

  // 3. Generate project files using the template engine
  logger.info('Generating project files...');
  const templatesPath = path.join(process.cwd(), 'server', 'templates', 'packs');
  const generator = new ProjectTemplateGenerator(templatesPath);
  const files = await generator.generateProject(options.projectConfig);

  if (files.length === 0) {
    throw new GitHubServiceError(
      'No files were generated. Check your project configuration.',
      'NO_FILES_GENERATED'
    );
  }

  logger.info(`Generated ${files.length} files, pushing to GitHub...`);

  // 4. Push all files in a single commit
  const filesCount = await pushFilesToRepo(
    octokit,
    repoInfo.owner,
    repoInfo.repo,
    repoInfo.defaultBranch,
    files
  );

  logger.info(`Successfully pushed ${filesCount} files to ${repoInfo.htmlUrl}`);

  return {
    repoUrl: repoInfo.htmlUrl,
    cloneUrl: repoInfo.cloneUrl,
    fullName: `${repoInfo.owner}/${repoInfo.repo}`,
    filesCount,
    defaultBranch: repoInfo.defaultBranch,
  };
}

/**
 * Custom error class for GitHub service errors
 */
export class GitHubServiceError extends Error {
  public readonly errorCode: string;

  constructor(message: string, errorCode: string) {
    super(message);
    this.name = 'GitHubServiceError';
    this.errorCode = errorCode;
  }
}
